"""Overcooked order queue support.

Provides order queue tick logic and table builders. All pot/container
mechanics (interaction branches, tick handler, extra state, static tables)
are now auto-generated by the Container/Recipe declarative system in
``cogrid.core.containers`` and composed by ``cogrid.core.autowire``.

This module contains only order-queue-specific code:

- ``build_order_tick`` -- factory that closes over order config and returns a tick function
- ``build_order_extra_state`` -- initialize order queue arrays
"""

from cogrid.backend import xp
from cogrid.backend.array_ops import set_at_2d


def build_order_extra_state(order_config):
    """Initialize order queue arrays from config.

    Parameters
    ----------
    order_config : dict
        Must contain ``"max_active"``.

    Returns:
    -------
    dict
        Order queue arrays keyed with ``overcooked.`` prefix.
    """
    import numpy as _np

    max_active = order_config["max_active"]
    return {
        "overcooked.order_recipe": _np.full((max_active,), -1, dtype=_np.int32),
        "overcooked.order_timer": _np.zeros((max_active,), dtype=_np.int32),
        "overcooked.order_n_expired": _np.int32(0),
    }


def build_order_tick(order_config, recipe_results):
    """Factory that returns an order-queue tick function.

    Pre-computes spawn probabilities and time limit from *order_config*
    and closes over them so the returned ``tick`` never reads from
    ``static_tables``.

    Parameters
    ----------
    order_config : dict or None
        If None, returns a no-op tick. Otherwise must contain
        ``spawn_probs`` (dict mapping result name to probability),
        ``max_active`` (default 3), ``time_limit`` (default 200).
    recipe_results : list[str]
        Ordered list of recipe result names (e.g. ``["onion_soup", "tomato_soup"]``)
        matching the recipe index ordering from ``Pot.recipes``.

    Returns:
    -------
    callable
        ``tick(state, scope_config) -> EnvState``
    """
    import numpy as _np

    if order_config is None:

        def noop_tick(state, scope_config):
            return state

        return noop_tick

    time_limit = _np.int32(order_config.get("time_limit", 200))
    spawn_probs_dict = order_config["spawn_probs"]

    n_recipes = len(recipe_results)
    spawn_probs_np = _np.zeros(n_recipes, dtype=_np.float32)
    for name, prob in spawn_probs_dict.items():
        idx = recipe_results.index(name)
        spawn_probs_np[idx] = prob

    assert _np.all(spawn_probs_np >= 0), "All spawn probabilities must be >= 0"
    assert float(_np.sum(spawn_probs_np)) <= 1.0 + 1e-6, (
        f"spawn_probs must sum to <= 1.0, got {float(_np.sum(spawn_probs_np))}"
    )

    def tick(state, scope_config):
        """Advance order timers: countdown, expiry, and probabilistic spawning."""
        import dataclasses

        from cogrid.backend._dispatch import get_backend

        if "overcooked.order_recipe" not in state.extra_state:
            return state

        new_extra = dict(state.extra_state)

        order_recipe = new_extra["overcooked.order_recipe"]
        order_timer = new_extra["overcooked.order_timer"]
        order_n_expired = new_extra["overcooked.order_n_expired"]

        max_active = order_recipe.shape[0]

        # (1) Decrement active order timers
        active = order_recipe != -1
        new_order_timer = xp.where(active, order_timer - 1, order_timer)

        # (2) Clear expired orders (timer reached 0)
        expired = active & (new_order_timer <= 0)
        order_recipe = xp.where(expired, -1, order_recipe)
        new_order_timer = xp.where(expired, 0, new_order_timer)
        order_n_expired = order_n_expired + xp.sum(expired).astype(xp.int32)

        # (3) Probabilistic spawn per empty slot
        cdf = xp.cumsum(spawn_probs_np)  # (n_recipes,)

        if get_backend() == "jax":
            import jax

            key, subkey = jax.random.split(state.rng_key)
            rolls = jax.random.uniform(subkey, shape=(max_active,))
        else:
            rolls = xp.array(
                _np.random.default_rng().uniform(size=(max_active,)),
                dtype=xp.float32,
            )
            key = state.rng_key

        # hit[i, r] = True if slot i's roll falls in recipe r's CDF bucket
        hit = rolls[:, None] < cdf[None, :]  # (max_active, n_recipes)
        any_hit = xp.any(hit, axis=1)  # did this slot spawn?
        sampled_recipe = xp.argmax(hit.astype(xp.int32), axis=1)

        empty = order_recipe == -1
        spawn_mask = empty & any_hit

        order_recipe = xp.where(spawn_mask, sampled_recipe, order_recipe)
        new_order_timer = xp.where(spawn_mask, time_limit, new_order_timer)

        new_extra["overcooked.order_recipe"] = order_recipe
        new_extra["overcooked.order_timer"] = new_order_timer
        new_extra["overcooked.order_n_expired"] = order_n_expired

        return dataclasses.replace(state, extra_state=new_extra, rng_key=key)

    return tick


# ---------------------------------------------------------------------------
# Order queue HUD rendering
# ---------------------------------------------------------------------------

# Recipe index → display color (RGB).
_RECIPE_COLORS = [
    (255, 200, 50),  # recipe 0 (onion soup) – golden yellow
    (220, 50, 50),  # recipe 1 (tomato soup) – red
]
_EMPTY_COLOR = (80, 80, 80)
_BG_COLOR = (50, 50, 50)
_URGENT_COLOR = (255, 80, 80)


def build_order_hud_fn(order_config):
    """Return a HUD function that extracts order bar specs from env state.

    The returned function has signature::

        hud_fn(env_state, scope_config) -> list[dict] | None

    Each dict has keys ``progress`` (0-1 float), ``color`` (RGB tuple),
    and ``bg_color`` (RGB tuple).
    """
    time_limit = order_config.get("time_limit", 200)

    def hud_fn(env_state, scope_config):
        import numpy as _np

        extra = env_state.extra_state
        order_recipe = extra.get("overcooked.order_recipe")
        if order_recipe is None:
            return None

        order_timer = extra["overcooked.order_timer"]
        bars = []
        for i in range(len(order_recipe)):
            recipe_idx = int(_np.array(order_recipe[i]))
            timer = int(_np.array(order_timer[i]))
            if recipe_idx < 0:
                bars.append({"progress": 0, "color": _EMPTY_COLOR, "bg_color": _BG_COLOR})
            else:
                progress = timer / time_limit
                color = _RECIPE_COLORS[recipe_idx % len(_RECIPE_COLORS)]
                if progress < 0.2:
                    color = _URGENT_COLOR
                bars.append({"progress": progress, "color": color, "bg_color": _BG_COLOR})
        return bars

    return hud_fn


# ---------------------------------------------------------------------------
# Target recipe system
# ---------------------------------------------------------------------------


def build_target_recipe_extra_state(config):
    """Initialize target-recipe indicator and button arrays from config.

    Scans ``parsed_arrays`` for ``R`` (RecipeIndicator) and ``L``
    (ButtonIndicator) positions and returns extra-state arrays for the
    target recipe system.

    Parameters
    ----------
    config : dict
        Must contain ``"target_recipes"`` (list of recipe name strings).

    Returns:
    -------
    callable
        ``fn(parsed_arrays, scope) -> dict`` producing initial extra-state.
    """
    import numpy as _np

    target_recipes = config["target_recipes"]

    def init_fn(parsed_arrays, scope):
        # Find R (RecipeIndicator) and L (ButtonIndicator) positions
        indicator_rows, indicator_cols = _np.where(parsed_arrays == "R")
        indicator_positions = _np.stack([indicator_rows, indicator_cols], axis=1).astype(_np.int32)

        button_rows, button_cols = _np.where(parsed_arrays == "L")
        button_positions = _np.stack([button_rows, button_cols], axis=1).astype(_np.int32)

        n_buttons = button_positions.shape[0]

        # Sample initial target recipe uniformly
        initial_idx = _np.random.randint(0, len(target_recipes))

        return {
            "overcooked.target_recipe": _np.int32(initial_idx),
            "overcooked.delivery_occurred": _np.int32(0),
            "overcooked.button_timer": _np.zeros((n_buttons,), dtype=_np.int32),
            "overcooked.button_positions": button_positions,
            "overcooked.indicator_positions": indicator_positions,
        }

    return init_fn


def build_target_recipe_tick(config):
    """Factory that returns a tick function for the target recipe system.

    The tick handles button timer countdown, recipe/button indicator sync
    into ``object_state_map``, and optional recipe resampling on delivery.

    Parameters
    ----------
    config : dict
        Keys: ``target_recipes`` (list[str]), ``resample_on_delivery`` (bool),
        ``indicator_activation_time`` (int, default 10).

    Returns:
    -------
    callable
        ``tick(state, scope_config) -> EnvState``
    """
    import numpy as _np

    target_recipes = config["target_recipes"]
    resample_on_delivery = config.get("resample_on_delivery", False)
    _indicator_activation_time = config.get("indicator_activation_time", 10)
    n_recipes = len(target_recipes)

    def tick(state, scope_config):
        """Advance button timers, sync indicators, and optionally resample recipe."""
        import dataclasses

        from cogrid.backend._dispatch import get_backend

        new_extra = dict(state.extra_state)

        target_recipe = new_extra["overcooked.target_recipe"]
        button_timer = new_extra["overcooked.button_timer"]
        button_positions = new_extra["overcooked.button_positions"]
        indicator_positions = new_extra["overcooked.indicator_positions"]

        # (1) Button timer countdown: decrement where > 0
        new_button_timer = xp.where(button_timer > 0, button_timer - 1, button_timer)

        # (2) Recipe indicator sync: write target_recipe + 1 at all indicator positions
        osm = state.object_state_map
        recipe_val = target_recipe + 1  # 0 = inactive, 1+ = recipe index + 1
        for i in range(indicator_positions.shape[0]):
            r, c = indicator_positions[i, 0], indicator_positions[i, 1]
            osm = set_at_2d(osm, r, c, recipe_val)

        # (3) Button indicator sync: write recipe+1 where timer > 0, 0 where timer == 0
        for i in range(button_positions.shape[0]):
            r, c = button_positions[i, 0], button_positions[i, 1]
            btn_val = xp.where(new_button_timer[i] > 0, recipe_val, xp.int32(0))
            osm = set_at_2d(osm, r, c, btn_val)

        new_extra["overcooked.button_timer"] = new_button_timer

        # (4) Recipe resampling on delivery
        # Detect delivery via a flag set by TargetRecipeDeliveryReward
        # or by checking if any agent's inventory was cleared at a delivery zone.
        # For now, resample whenever a delivery_occurred flag is set in extra_state.
        new_key = state.rng_key
        delivery_flag = new_extra.get("overcooked.delivery_occurred", None)
        if resample_on_delivery and delivery_flag is not None:
            did_deliver = delivery_flag > 0
            if get_backend() == "jax":
                import jax

                new_key, subkey = jax.random.split(state.rng_key)
                new_idx = jax.random.randint(
                    subkey,
                    shape=(),
                    minval=0,
                    maxval=n_recipes,
                )
                new_extra["overcooked.target_recipe"] = xp.where(
                    did_deliver,
                    new_idx,
                    target_recipe,
                )
            else:
                if bool(did_deliver):
                    new_extra["overcooked.target_recipe"] = _np.int32(
                        _np.random.randint(0, n_recipes),
                    )

            # Reset the flag
            new_extra["overcooked.delivery_occurred"] = xp.int32(0)

        return dataclasses.replace(
            state,
            extra_state=new_extra,
            object_state_map=osm,
            rng_key=new_key,
        )

    return tick


def build_branch_activate_button(activation_time=10):
    """Factory that returns a branch function for button activation.

    The branch fires when: agent toggles, faces a button, has empty hands,
    and the button is not already active (timer == 0).

    Parameters
    ----------
    activation_time : int
        Number of ticks the button stays active after pressing.

    Returns:
    -------
    callable
        ``branch(ctx) -> (should_apply, changes)``
    """
    from cogrid.backend.array_ops import set_at
    from cogrid.core.pipeline.context import find_facing_instance

    def branch(ctx):
        is_toggle = ctx.action == ctx.action_id.toggle
        empty_hands = ctx.held_item == -1

        # Find which button the agent faces
        btn_idx, faces_button = find_facing_instance(
            ctx.button_positions, ctx.facing_row, ctx.facing_col
        )

        # Check button is not already active
        button_not_active = ctx.button_timer[btn_idx] == 0

        should_apply = ctx.can_interact & is_toggle & faces_button & empty_hands & button_not_active

        new_timer = set_at(ctx.button_timer, btn_idx, xp.int32(activation_time))

        return should_apply, {"button_timer": new_timer}

    return branch


def build_branch_flag_delivery():
    """Return a branch that sets a delivery_occurred flag on open delivery zones.

    This branch fires alongside the standard consume branch. It does not
    change any grid state — it only sets a flag in extra_state so the
    tick function can detect that a delivery occurred and resample the
    target recipe.
    """

    def branch(ctx):
        dz_id = ctx.type_ids.get("open_delivery_zone", -1)
        is_pickup_drop = ctx.action == ctx.action_id.pickup_drop
        faces_dz = ctx.facing_type == dz_id
        has_item = ctx.held_item != -1

        should_apply = ctx.can_interact & is_pickup_drop & faces_dz & has_item
        new_flag = xp.where(should_apply, xp.int32(1), ctx.delivery_occurred)

        return should_apply, {"delivery_occurred": new_flag}

    return branch
