"""Overcooked grid object types (food, pots, plates, delivery zones)."""

import math

from cogrid.core import constants
from cogrid.core import objects as grid_object
from cogrid.core.objects import register_object_type
from cogrid.core.objects.containers import Container
from cogrid.core.objects.when import when
from cogrid.envs.overcooked.recipes import Recipe
from cogrid.rendering.tile_surface import TileSurface


def _rotate_around(px: float, py: float, cx: float, cy: float, theta: float) -> tuple[float, float]:
    """Rotate (px, py) by theta radians around (cx, cy)."""
    cos_t, sin_t = math.cos(theta), math.sin(theta)
    return (
        cx + (px - cx) * cos_t - (py - cy) * sin_t,
        cy + (px - cx) * sin_t + (py - cy) * cos_t,
    )


@register_object_type("onion", scope="overcooked")
class Onion(grid_object.GridObj):
    """A single onion ingredient."""

    color = constants.Colors.Yellow
    char = "o"
    can_pickup = when()

    def __init__(self, *args, **kwargs):
        """Initialize with default state."""
        super().__init__(state=0)

    def render(self, surface: TileSurface) -> None:
        """Draw a yellow circle."""
        surface.circle(x=0.5, y=0.5, radius=0.3, color=self.color)


@register_object_type("tomato", scope="overcooked")
class Tomato(grid_object.GridObj):
    """A single tomato ingredient."""

    color = constants.Colors.Red
    char = "t"
    can_pickup = when()

    def __init__(self, *args, **kwargs):
        """Initialize with default state."""
        super().__init__(state=0)

    def render(self, surface: TileSurface) -> None:
        """Draw a red circle."""
        surface.circle(x=0.5, y=0.5, radius=0.3, color=self.color)


class _BaseStack(grid_object.GridObj):
    """Base class for infinite dispenser stacks.

    Subclasses set class attributes only: object_id, color, char, produces.
    All behavior (pick_up_from, render) is inherited.
    """

    produces: str = None
    scope: str = "overcooked"
    background_color = constants.Colors.LightBrown
    can_pickup_from = when()

    def render(self, surface: TileSurface) -> None:
        """Draw three stacked circles using self.color."""
        surface.circle(x=0.25, y=0.3, radius=0.2, color=self.color)
        surface.circle(x=0.75, y=0.3, radius=0.2, color=self.color)
        surface.circle(x=0.50, y=0.7, radius=0.2, color=self.color)


@register_object_type("onion_stack", scope="overcooked")
class OnionStack(_BaseStack):
    """An infinite pile of onions."""

    color = constants.Colors.Yellow
    char = "O"
    produces = "onion"


@register_object_type("tomato_stack", scope="overcooked")
class TomatoStack(_BaseStack):
    """An infinite pile of tomatoes."""

    color = constants.Colors.Red
    char = "T"
    produces = "tomato"


@register_object_type("pot", scope="overcooked")
class Pot(grid_object.GridObj):
    """A cooking pot that accepts ingredients and produces soup.

    Behavior is fully auto-generated by the Container + Recipe system.
    The ``container`` and ``recipes`` class attrs replace ~180 lines of
    classmethods + config.py functions.
    """

    color = constants.Colors.Grey
    background_color = constants.Colors.LightBrown
    char = "U"

    container = Container(capacity=3, pickup_requires="plate")
    recipes = [
        Recipe(
            ["onion", "onion", "onion"],
            result="onion_soup",
            cook_time=30,
            reward=1.0,
        ),
        Recipe(
            ["tomato", "tomato", "tomato"],
            result="tomato_soup",
            cook_time=30,
            reward=1.0,
        ),
    ]

    capacity: int = 3  # backward compat alias for container.capacity

    @classmethod
    def build_static_tables(cls):
        """Build recipe lookup tables for the interaction and reward systems."""
        from cogrid.envs.overcooked.recipes import build_recipe_static_tables

        return build_recipe_static_tables("pot", cls.recipes, scope="overcooked")

    def __init__(self, state: int = 0, **kwargs):
        """Initialize pot with empty contents and default timer."""
        super().__init__(state=state)
        self.objects_in_pot: list[grid_object.GridObj] = []
        self.cooking_timer: int = 30

    def render(self, surface: TileSurface) -> None:
        """Draw pot with lid, ingredient dots, and progress bar."""
        is_full = len(self.objects_in_pot) == self.capacity
        is_cooking = is_full and self.cooking_timer > 0
        is_cooked = is_full and self.cooking_timer == 0
        has_ingredients = len(self.objects_in_pot) > 0
        pot_open = not is_cooking and not is_cooked and has_ingredients

        # Ingredient circles above pot
        coords = [(0.23, 0.33), (0.77, 0.33), (0.50, 0.33)]
        for i, grid_obj in enumerate(self.objects_in_pot):
            cx, cy = coords[i]
            surface.circle(x=cx, y=cy, radius=0.13, color=grid_obj.color)

        # Pot body
        surface.rect(x=0.10, y=0.33, w=0.80, h=0.57, color=(0, 0, 0))

        # Lid and handle as polygon rects so we can rotate when the pot is open
        lid_pts = [(0.1, 0.21), (0.9, 0.21), (0.9, 0.25), (0.1, 0.25)]
        handle_pts = [(0.4, 0.16), (0.6, 0.16), (0.6, 0.21), (0.4, 0.21)]
        if pot_open:
            theta = -0.1 * math.pi
            lid_pts = [_rotate_around(px, py, 0.1, 0.25, theta) for px, py in lid_pts]
            handle_pts = [_rotate_around(px, py, 0.1, 0.25, theta) for px, py in handle_pts]
        surface.polygon(points=lid_pts, color=(0, 0, 0))
        surface.polygon(points=handle_pts, color=(0, 0, 0))

        # Progress bar while cooking or after cooked
        if is_cooking or is_cooked:
            cook_time = self.recipes[0].cook_time if self.recipes else 30
            progress = 0.1 + (0.9 - 0.1) * (1 - self.cooking_timer / cook_time)
            surface.rect(
                x=0.10,
                y=0.83,
                w=progress - 0.10,
                h=0.05,
                color=constants.Colors.Green,
            )

    def encode(self, encode_char: bool = True, scope: str = "global"):
        """Encode pot state including contents and timer for tile cache."""
        char, _, state = super().encode(encode_char=encode_char, scope=scope)
        content_ids = tuple(sorted(getattr(obj, "object_id", "") for obj in self.objects_in_pot))
        extra = (len(self.objects_in_pot), content_ids, self.cooking_timer)
        return (char, extra, state)


@register_object_type("onion_soup_stack", scope="overcooked")
class OnionSoupStack(_BaseStack):
    """An infinite dispenser of pre-made onion soups."""

    color = constants.Colors.LightBrown
    char = "1"
    produces = "onion_soup"


@register_object_type("tomato_soup_stack", scope="overcooked")
class TomatoSoupStack(_BaseStack):
    """An infinite dispenser of pre-made tomato soups."""

    color = constants.Colors.Red
    char = "2"
    produces = "tomato_soup"


@register_object_type("plate_stack", scope="overcooked")
class PlateStack(_BaseStack):
    """An infinite stack of plates for picking up soup."""

    color = constants.Colors.White
    char = "="
    produces = "plate"


def make_ingredient_and_stack(
    ingredient_name: str,
    ingredient_char: str,
    ingredient_color,
    stack_name: str,
    stack_char: str,
    scope: str = "overcooked",
) -> tuple:
    """Create and register a new ingredient + stack pair at runtime.

    Must be called BEFORE ``_build_interaction_tables`` runs (i.e. before
    env autowire). Typical call sites: at module-import time in a custom
    env module, or during env config setup before ``build_overcooked_extra_state``.

    Parameters
    ----------
    ingredient_name : str
        Object ID for the ingredient (e.g. "mushroom").
    ingredient_char : str
        Single character for grid encoding. Must be unique within *scope*.
    ingredient_color : tuple or list
        RGB color for rendering.
    stack_name : str
        Object ID for the stack (e.g. "mushroom_stack").
    stack_char : str
        Single character for grid encoding. Must be unique within *scope*.
    scope : str
        Registry scope (default "overcooked").

    Returns:
    -------
    tuple
        (IngredientCls, StackCls) -- the two newly created and registered classes.
    """
    # --- Create ingredient class ---
    IngredientCls = type(
        ingredient_name.title().replace("_", ""),
        (grid_object.GridObj,),
        {
            "color": ingredient_color,
            "char": ingredient_char,
            "can_pickup": when(),
        },
    )

    def _ingredient_init(self, *args, **kwargs):
        grid_object.GridObj.__init__(self, state=0)

    def _ingredient_render(self, surface: TileSurface) -> None:
        surface.circle(x=0.5, y=0.5, radius=0.3, color=self.color)

    IngredientCls.__init__ = _ingredient_init
    IngredientCls.render = _ingredient_render

    register_object_type(ingredient_name, scope=scope)(IngredientCls)

    # --- Create stack class (inherits can_pickup_from from _BaseStack) ---
    StackCls = type(
        stack_name.title().replace("_", ""),
        (_BaseStack,),
        {
            "color": ingredient_color,
            "char": stack_char,
            "produces": ingredient_name,
        },
    )

    register_object_type(stack_name, scope=scope)(StackCls)

    return (IngredientCls, StackCls)


@register_object_type("plate", scope="overcooked")
class Plate(grid_object.GridObj):
    """A plate used to serve completed soups."""

    color = constants.Colors.White
    char = "P"
    can_pickup = when()

    def __init__(self, *args, **kwargs):
        """Initialize with default state."""
        super().__init__(state=0)

    def render(self, surface: TileSurface) -> None:
        """Draw a white circle."""
        surface.circle(x=0.5, y=0.5, radius=0.5, color=self.color)


@register_object_type("delivery_zone", scope="overcooked")
class DeliveryZone(grid_object.GridObj):
    """A zone where agents deliver completed soups for reward."""

    color = constants.Colors.Green
    char = "@"
    can_place_on = when(agent_holding=["onion_soup", "tomato_soup"])
    consumes_on_place = True

    def __init__(self, *args, **kwargs):
        """Initialize with default state."""
        super().__init__(state=0)


@register_object_type("onion_soup", scope="overcooked")
class OnionSoup(grid_object.GridObj):
    """A completed onion soup, ready for delivery."""

    color = constants.Colors.LightBrown
    char = "S"
    can_pickup = when()

    def __init__(self, *args, **kwargs):
        """Initialize with default state."""
        super().__init__(state=0)

    def render(self, surface: TileSurface) -> None:
        """Draw a plate with soup inside."""
        surface.circle(x=0.5, y=0.5, radius=0.5, color=Plate.color)
        surface.circle(x=0.5, y=0.5, radius=0.3, color=self.color)


@register_object_type("tomato_soup", scope="overcooked")
class TomatoSoup(grid_object.GridObj):
    """A completed tomato soup, ready for delivery."""

    color = constants.Colors.Red
    char = "!"
    can_pickup = when()

    def __init__(self, *args, **kwargs):
        """Initialize with default state."""
        super().__init__(state=0)

    def render(self, surface: TileSurface) -> None:
        """Draw a plate with soup inside."""
        surface.circle(x=0.5, y=0.5, radius=0.5, color=Plate.color)
        surface.circle(x=0.5, y=0.5, radius=0.3, color=self.color)
